---
services:
    mysqldb:
      container_name: mysqldb
      image: pravallikavudata/myapp:db
      ports:
        - "3306:3306"

    application:
      container_name: mycont
      image: pravallikavudata/myapp:app
      ports:
        - "1234:80"
      depends_on:
        - mysqldb
      
    
